name: MVVM
on:
  push:
    branches: [ "main", "V1" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        configuration: [Debug, Release]
    runs-on: ${{ matrix.os }}
    env:
      Solution_Name: Project/FW4di.Dotnet.MVVM.sln
      Test_Project_Path: Project/FW4di.Dotnet.MVVM.Tests/FW4di.Dotnet.MVVM.Tests.csproj
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
        
    - name: Clear NuGet cache (Windows)
      if: runner.os == 'Windows'
      run: dotnet nuget locals all --clear
      continue-on-error: true
      
    - name: Clear NuGet cache (Unix)
      if: runner.os != 'Windows'
      run: dotnet nuget locals all --clear
      continue-on-error: true
      
    - name: List NuGet sources
      run: dotnet nuget list source
      
    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }} --disable-parallel --verbosity normal
      timeout-minutes: 10
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        
    - name: Build solution
      run: dotnet build ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }} --no-restore
      
    - name: Run tests
      run: dotnet test ${{ env.Test_Project_Path }} --configuration ${{ matrix.configuration }} --no-build --verbosity normal